import type { CalendarioUsuarioRow } from './calendario-usuario.model';
import { createDefaultDisponibilidad } from './calendario-usuario.model';

export const CALENDARIOS_MOCK: CalendarioUsuarioRow[] = [
  {
    id: '1',
    tipo: 'interno',
    nombre: 'Tom Chatt',
    telefono: '+52 4839203948',
    correo: 'carlos.perez@email.com',
    grupos: ['Atención al Cliente', 'Ventas Ecuador'],
    tiposEvento: 2,
    estado: 'activo',
    disponibilidad: createDefaultDisponibilidad(),
  },
  {
    id: '2',
    tipo: 'interno',
    nombre: 'Humberto Díaz',
    telefono: '+52 4810239402',
    correo: 'humberto.superadmin@email.com',
    grupos: ['Atención al Cliente'],
    tiposEvento: 1,
    estado: 'activo',
    disponibilidad: createDefaultDisponibilidad(),
  },
  {
    id: '3',
    tipo: 'externo',
    nombre: 'Dr. Juan Pérez',
    telefono: '+52 5584930293',
    correo: 'juan.perez@dentalsonria.com',
    grupos: ['Soporte y Consultas Médicas'],
    tiposEvento: 1,
    estado: 'activo',
    citasFuturas: 3,
    disponibilidad: createDefaultDisponibilidad(),
  },
  {
    id: '4',
    tipo: 'externo',
    nombre: 'Ing. Carlos Torres',
    telefono: '+52 5592839402',
    correo: 'carlos.torres@externo.com',
    grupos: ['Ventas Vehículos Nuevos'],
    tiposEvento: 1,
    estado: 'activo',
    citasFuturas: 3,
    disponibilidad: createDefaultDisponibilidad(),
  },
  {
    id: '5',
    tipo: 'externo',
    nombre: 'Dra. Ana María',
    telefono: '+52 5519283940',
    correo: 'ana.maria@dentalsonria.com',
    grupos: ['Soporte y Consultas Médicas'],
    tiposEvento: 1,
    estado: 'desactivado',
    disponibilidad: createDefaultDisponibilidad(),
  },
];
